[package]
name = "conway-life"
version = "0.1.0"
edition = "2021"
author = ["chuj <1768485949@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
nannou_egui = "0.5"
thiserror = "1.0"
